config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users
  devise_for :users

  root 'artists#index'
  resources :artists, only: :show
  resources :users, only: :show
  resources :songs, only: :show do
    resources :calls, only: [:new, :create, :show, :edit, :update, :destroy] do
      resources :comments, only: [:new, :create, :edit, :update, :destroy]
    end
    collection do
      get 'search'
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :call
  belongs_to :user
  attr_accessor :comment_index
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_song_call, only: [:new, :create, :edit, :update]
  before_action :authenticate_user!, :only => [:new, :edit]
  def new
    @comment = Comment.new
  end

  def create
    Comment.create(create_params)
    redirect_to song_call_path(@song, @call), :flash => {:notice => "コメントを投稿しました！！"}
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if current_user.id == @comment.user_id
      @comment.update(create_params)
      redirect_to song_call_path(@song, @call), :flash => {:notice => "コメントを編集しました！！"}
    else
      redirect_to song_call_path(@song, @call)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to :back
  end


  private
  def create_params
    params.require(:comment).permit(:text).merge(call_id: params[:call_id], user_id: current_user.id)
  end

  def set_song_call
    @song = Song.find(params[:song_id])
    @call = Call.find(params[:call_id])
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Number : <%= comment.comment_index %>  投稿者 : <button class="btn btn-default" type="submit"><a href="/users/<%= comment.user_id %>"><%= comment.user.nickname %>
  </a></button>
  </div>

<ul class="list-group">
    <li class="list-group-item">投稿日時 : <%= comment.created_at.strftime("%Y年%m月%d日 %H時%M分") %></li>

    <% if comment.created_at != comment.updated_at %>

    <li class="list-group-item">更新日時 : <%= comment.updated_at.strftime("%Y年%m月%d日 %H時%M分") %></li>

<% end %>

  </ul>
  <div class="panel-body">
    コメント : <%= comment.text %>
  </div>


  <div class="panel-footer">

  <% if user_signed_in? && current_user.id == comment.user_id %>


    <button class="btn btn-default" type="submit">


<%= link_to '編集する', edit_song_call_comment_path(@call.song.id, @call.id, comment.id) , method: :get %>

    </button>

    <button class="btn btn-default" type="submit">
  <%= link_to '削除する', song_call_comment_path(@call.song.id, @call.id, comment.id) , method: :delete %>

    </button>
  <% end %>
  </div>
</div>

app/views/comments/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>コメント編集フォーム</h4>
  </div>
  <div class="panel-footer">
<%= form_for [@song, @call, @comment] do |f| %>

<div class="form-group">
  <%= f.text_area :text, placeholder: 'わかりやすいですね！', id: 'comment', class: "form-control call_text" %>
</div>

  <%= button_tag type: "submit", class: "btn btn-primary" do %>
    編集する!!
  <% end %>
<% end %>

app/views/comments/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>コメント投稿フォーム</h4>
  </div>
  <div class="panel-footer">
<%= form_for [@song, @call, @comment] do |f| %>

<div class="form-group">
  <%= f.text_area :text, placeholder: 'わかりやすいですね！', id: 'comment', class: "form-control call_text" %>
</div>

  <%= button_tag type: "submit", class: "btn btn-primary" do %>
    投稿する!!
  <% end %>
<% end %>