config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users
  devise_for :users

  root 'artists#index'
  resources :artists, only: :show
  resources :users, only: :show
  resources :songs, only: :show do
    resources :calls, only: [:new, :create, :show, :edit, :update, :destroy] do
      resources :comments, only: [:new, :create, :edit, :update, :destroy]
    end
    collection do
      get 'search'
    end
  end

end

app/models/call.rb
class Call < ActiveRecord::Base
  belongs_to :song
  belongs_to :user
  has_many :comments, :dependent => :delete_all
  attr_accessor :call_index
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
before_action :authenticate_user!, :only => [:new, :edit]


  def new
    @song = Song.find(params[:song_id])
    @call = Call.new
  end

  def create
    @song = Song.find(params[:song_id])
    if Call.find_by(song_id: @song.id, user_id: current_user.id)
      redirect_to song_path(@song), :flash => {:error => "同じ曲にコールを2回以上投稿することはできません！！"}

    else
      Call.create(create_params)
      redirect_to song_path(@song), :flash => {:notice => "コールを投稿しました！！"}
    end
  end

  def show
    @call = Call.find(params[:id])
    @song = @call.song
    @comments = @call.comments.page(params[:page]).per(5)
    page_index = params[:page] ? (params[:page].to_i-1) * 5 + 1 : 1
    @comment_number = @comments.each.with_index(page_index) do |comment, i|
      comment.comment_index = i
    end
  end

  def edit
    @song = Song.find(params[:song_id])
    @call = Call.find(params[:id])

  end

  def update
    @song = Song.find(params[:song_id])
    @call = Call.find(params[:id])
    if current_user.id == @call.user_id
      @call.update(create_params)
      redirect_to song_path(@song), :flash => {:notice => "コールを編集しました！！"}
    else
      redirect_to song_path(@song)
    end
  end

  def destroy
    @call = Call.find(params[:id])
    @call.destroy
    redirect_to :back
  end

  private
  def create_params
    params.require(:call).permit(:movie_url, :text).merge(song_id: params[:song_id], user_id: current_user.id)
  end

end

app/helpers/calls_helper.rb
module CallsHelper
end

app/views/calls/_call.html.erb
<div class="panel panel-default">
  <div class="panel-heading">投稿者 <%= call.call_index %> :
    <button class="btn btn-default" type="submit"><a href="/users/<%= call.user.id %>">
       <%= call.user.nickname %>
     </a></button>
  </div>
  <ul class="list-group">
    <li class="list-group-item">投稿日時 : <%= call.created_at.strftime("%Y年%m月%d日 %H時%M分") %></li>

    <% if call.created_at != call.updated_at %>

    <li class="list-group-item">更新日時 : <%= call.updated_at.strftime("%Y年%m月%d日 %H時%M分") %></li>

<% end %>

  </ul>
  <div class="panel-body">
    <div class="media">
      <div class="media-left">
          <iframe width="240" height="180" src="<%= call.movie_url.gsub('watch?v=', 'embed/') %>" frameborder="1" allowfullscreen></iframe>
      </div>
      <div class="media-body">
        <h4 class="media-heading">コールの説明 : <%= simple_format(call.text) %></h4>
      </div>
    </div>
  </div>

  <div class="panel-footer">
    <button class="btn btn-default" type="submit"><a href="/songs/<%= @song.id %>/calls/<%= call.id %>">コールの詳細ページへ</a></button>
    <% if user_signed_in? && current_user.id == call.user_id %>
    <button class="btn btn-default" type="submit"><%= link_to '編集する', edit_song_call_path(call.song.id, call.id) , method: :get %></button>
    <button class="btn btn-default" type="submit"> <%= link_to '削除する', song_call_path(call.song.id, call.id) , method: :delete %></button>
    <% end %>
  </div>
</div>

app/views/calls/_callshow.html.erb
<div class="panel panel-default">
  <div class="panel-heading">投稿者 <%= @call.call_index %> :
    <button class="btn btn-default" type="submit"><a href="/users/<%= @call.user.id %>">
       <%= @call.user.nickname %>
     </a></button>
  </div>
  <ul class="list-group">
    <li class="list-group-item">投稿日時 : <%= @call.created_at.strftime("%Y年%m月%d日 %H時%M分") %></li>

    <% if @call.created_at != @call.updated_at %>

    <li class="list-group-item">更新日時 : <%= @call.updated_at.strftime("%Y年%m月%d日 %H時%M分") %></li>

<% end %>

  </ul>
  <div class="panel-body">
    <div class="media">
      <div class="media-left">
          <iframe width="240" height="180" src="<%= @call.movie_url.gsub('watch?v=', 'embed/') %>" frameborder="1" allowfullscreen></iframe>
      </div>
      <div class="media-body">
        <h4 class="media-heading">コールの説明 : <%= simple_format(@call.text) %></h4>
      </div>
    </div>
  </div>

  <div class="panel-footer">

    <% if user_signed_in? %>

    <button class="btn btn-default" type="submit"><%= link_to "このコールにコメントする", new_song_call_comment_path(@call.song.id, @call.id), method: :get %></button>

    <% end %>

    <% if user_signed_in? && current_user.id == @call.user_id %>
    <button class="btn btn-default" type="submit"><%= link_to '編集する', edit_song_call_path(@call.song.id, @call.id) , method: :get %></button>
    <button class="btn btn-default" type="submit"> <%= link_to '削除する', song_call_path(@call.song.id, @call.id) , method: :delete %></button>
    <% end %>
  </div>
</div>

app/views/calls/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>コール編集フォーム</h4>
  </div>
  <div class="panel-footer">
<%= form_for [@song, @call] do |f| %>

      <div class="form-group">
        <%= f.text_field :movie_url, placeholder: 'youtubeのurl', class: "form-control" %>
    </div>


      <div class="form-group">
  <%= f.text_area :text, placeholder: '00:09~ ヲイ！', id: 'call', class: "form-control call_text" %>
  </div>

  <%= button_tag type: "submit", class: "btn btn-primary" do %>
    編集する!!
  <% end %>
<% end %>

app/views/calls/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>コール投稿フォーム</h4>
  </div>
  <div class="panel-footer">
<%= form_for [@song, @call] do |f| %>

      <div class="form-group">
        <%= f.text_field :movie_url, placeholder: 'youtubeのurl', class: "form-control" %>
    </div>


      <div class="form-group">
  <%= f.text_area :text, placeholder: '00:09~ ヲイ！', id: 'call', class: "form-control call_text" %>
  </div>

  <%= button_tag type: "submit", class: "btn btn-primary" do %>
    投稿する!!
  <% end %>
<% end %>

app/views/calls/show.html.erb
  <%= render partial: "calls/callshow" %>




<div class="page-header">
  <h3>コメント一覧</h3>
</div>

    <% if @comments.present? %>
      <%= render partial: "comments/comment", collection: @comments %>
    <% else %>
      <p>このコールへのコメントはまだありません</p>
    <% end %>
<%= paginate(@comments) %>