config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users
  devise_for :users

  root 'artists#index'
  resources :artists, only: :show
  resources :users, only: :show
  resources :songs, only: :show do
    resources :calls, only: [:new, :create, :show, :edit, :update, :destroy] do
      resources :comments, only: [:new, :create, :edit, :update, :destroy]
    end
    collection do
      get 'search'
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hello!Otacalls!!</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
    <div class='col-xs-12'>
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">

          <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="/">Hello!OtaCalls</a></li>

            <% if user_signed_in? %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/users/<%= current_user.id %>"><%= current_user.nickname %>さんのマイページ</a></li>
              <li><%= link_to 'プロフィールを編集', edit_user_registration_path %></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>

            </ul>
          </li>
            <% else %>


              <li><%= link_to "ログイン", new_user_session_path, class: 'post' %></li>
              <li><%= link_to "新規登録", new_user_registration_path, class: 'post' %></li>
            <% end %>
          </ul>

          <form class="navbar-form navbar-right js-search-submit" role="search" accept-charset="utf-8" action="/songs/search" method="get">
              <div class="form-group">
                <input class="form-control search-width" name="keyword" placeholder="楽曲名を入力してください" type="text" value=""></div>
              <button title="検索" type="submit" class="btn btn-default">検索</button>
          </form>
        </div>
      </nav>
    </div>
  </header>

<div class="under_header">

<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

  <div class="content center-block">
    <div class="jumbotron">
      <div class="jumbotron_width center-block">
        <h1>Hello!OtaCalls!!</h1>
          <p>ハロプロ曲のコールを投稿するウェブサイトです!!</p>
      </div>
    </div>
    <div class="main_contents center-block">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

app/views/layouts/song_show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hello!Otacalls!!</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
    <div class='col-xs-12'>
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">

          <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="/">Hello!OtaCalls</a></li>

            <% if user_signed_in? %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/users/<%= current_user.id %>"><%= current_user.nickname %>さんのマイページ</a></li>
              <li><%= link_to 'プロフィールを編集', edit_user_registration_path %></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>

            </ul>
          </li>
                      <li><%= link_to "#{@song.name}のコールを投稿する", new_song_call_path(@song.id), method: :get %></li>

            <% else %>


              <li><%= link_to "ログイン", new_user_session_path, class: 'post' %></li>
              <li><%= link_to "新規登録", new_user_registration_path, class: 'post' %></li>
            <% end %>
          </ul>

          <form class="navbar-form navbar-right js-search-submit" role="search" accept-charset="utf-8" action="/songs/search" method="get">
              <div class="form-group">
                <input class="form-control" name="keyword" placeholder="楽曲名を入力してください" type="text" value=""></div>
              <button title="検索" type="submit" class="btn btn-default">検索</button>
          </form>
        </div>
      </nav>
    </div>
  </header>

<div class="under_header">

<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>


  <div class="content center-block">
    <div class="jumbotron">
      <div class="jumbotron_width center-block">
        <h1>Hello!OtaCalls!!</h1>
          <p>ハロプロ曲のコールを投稿するウェブサイトです!!</p>
      </div>
    </div>
    <div class="main_contents center-block">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>